#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_logout:
    path: /logout
    methods: GET
create:
  path: /admin/create-post
  controller: App\Controller\AdminController::createPost

view:
  path: /admin/view-post/{id}
  controller: App\Controller\AdminController::viewPost

show:
  path: /admin/show-post
  controller: App\Controller\AdminController::showPost

delete:
  path: /admin/delete-post/{id}
  controller: App\Controller\AdminController::deletePost

update:
  path: /admin/update-post/{id}
  controller: App\Controller\AdminController::updatePost

kms_froala_editor:
    resource: '@KMSFroalaEditorBundle/Resources/config/routing.yml'
    prefix:   /froalaeditor
show-email:
  path: /admin/show-email
  controller: App\Controller\ContactController::showEmail